apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
        - name: redis
          image: meidongauto-docker.pkg.coding.net/itsm/public/redis:latest
          resources: 
            limits:
              cpu: 1000m
              memory: 512Mi 
            requests: 
              cpu: 256m 
              memory: 256Mi
        - name: agent
          image: meidongauto-docker.pkg.coding.net/itsm/private/configagent:0.1
          resources: 
            limits:
              cpu: 1000m
              memory: 512Mi 
            requests: 
              cpu: 256m 
              memory: 256Mi
          volumeMounts:
            - name:  appname-volumes
              mountPath: /usr/app
              subPath: config.json
        - name: api
          image: meidongauto-docker.pkg.coding.net/itsm/private/project-appname-flask:0.1
          resources: 
            limits:
              cpu: 1000m
              memory: 512Mi 
            requests: 
              cpu: 512m 
              memory: 256Mi
          ports:
            - containerPort: 5000
      volumes:
        - name:  appname-volumes
          configMap:
            name: iappname-config
            defaultMode: 420
      nodeSelector:
        zone: group
      imagePullSecrets: 
        - name: YourSecrets


---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: appname
spec:
  scaleTargetRef:
    kind: Deployment
    name: appname
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: appname-config
data:
  config.json: |
    {
      "appname": "appname",   
      "etcd":{
          "host": [
            "127.0.0.1:2379"
          ]
          "user": "", 
          "pwd": "", 
          "root": "/appname/"
      },
      "config":{
          "item":{
              "appname:MYSQL_MASTER":"mysql+pymysql://user:password@195.168.0.222/dbname?&autocommit=true",
              ""
          },
          "etcdmap":{
              "MYSQL_MASTER": "appname:MYSQL_MASTER", 
          }
      }
    }



---

apiVersion: v1
kind: Service
metadata:
  name: project-appname-service
spec:
  type: NodePort
  ports:
  - name: api
    port: 30000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: appname
